#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

cleanup() {
  docker rm -f llrdc-webrtc-ull-test-standard llrdc-webrtc-ull-test-ull >/dev/null 2>&1 || true
}
trap cleanup EXIT

LLRDC_TARGET_FPS="${LLRDC_TARGET_FPS:-60}" \
LLRDC_TARGET_MAX_RES="${LLRDC_TARGET_MAX_RES:-720}" \
LLRDC_TARGET_BANDWIDTH_MBPS="${LLRDC_TARGET_BANDWIDTH_MBPS:-10}" \
LLRDC_TARGET_VIEWPORT_WIDTH="${LLRDC_TARGET_VIEWPORT_WIDTH:-1280}" \
LLRDC_TARGET_VIEWPORT_HEIGHT="${LLRDC_TARGET_VIEWPORT_HEIGHT:-720}" \
LLRDC_TARGET_VIDEO_CODEC="${LLRDC_TARGET_VIDEO_CODEC:-vp8}" \
LLRDC_ULL_WARMUP_TRIALS="${LLRDC_ULL_WARMUP_TRIALS:-5}" \
LLRDC_ULL_TRIALS="${LLRDC_ULL_TRIALS:-30}" \
LLRDC_ULL_MIN_VALID_TRIALS="${LLRDC_ULL_MIN_VALID_TRIALS:-25}" \
LLRDC_ASSERT_ULL_IMPROVES="${LLRDC_ASSERT_ULL_IMPROVES:-false}" \
LLRDC_ASSERT_ULL_IMPROVEMENT_MS="${LLRDC_ASSERT_ULL_IMPROVEMENT_MS:-8}" \
./test.sh tests/cpu/wayland_webrtc_ull.spec.ts "$@"
